RANDOM_MODE = 'random'
IMAGE_KEY = 'image'

# TODO: Parametrize in config
# Augmentations
CROP_PERSPECTIVE_P = 0.8
SCALE_X_P = 0.8
BRIGHT_CONTRAST_P = 1
CLAHE_P = 0.5
BLUR_LIMIT = 3
BLUR_P = 0.3
GAUSS_P = 0.3
DOWNSCALE_MIN = 0.3
DOWNSCALE_MAX = 0.9
DOWNSCALE_P = 0.5
DROPOUT_MIN_HOLES = 10
DROPOUT_MAX_HOLES = 20
DROPOUT_P = 0.3
