name: Build

on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - "*"

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install poetry
      run: pip install poetry

    - name: Install dependencies
      run: make setup_ws

    - name: Static code analysis
      run: make ci_static_code_analysis
